# Generated by Django 4.2.2 on 2023-06-20 10:14

import Music_site_app_remake_exam.my_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Pop Music', '1-Pop Music'), ('Jazz Music', '2-Jazz Music'), ('R&B Music', '3-R&B Music'), ('Rock Music', '4-Rock Music'), ('Country Music', '5-Country Music'), ('Dance Music', '6-Dance Music'), ('Hip Hop Music', '7-Hip Hop Music'), ('Other', '8-Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(default=0, validators=[Music_site_app_remake_exam.my_web.models.price_cannot_be_below_zero])),
            ],
        ),
    ]
