# Generated by Django 4.2.2 on 2023-06-20 11:51

import Music_site_app_remake_exam.my_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0002_albummodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='price',
            field=models.FloatField(validators=[Music_site_app_remake_exam.my_web.models.price_cannot_be_below_zero]),
        ),
    ]
